Update: Renamed namespaces
jonashoelzel/ZEISS_Verwaltungssystem pull request #102
Opened 2021-03-29 17:04 UTC by YeGaSoft

Delete: Unnecessary files
Fix: Bugs caused by renamed namespaces
Fix: Excel files won't be uploaded anymore to repo
Fix(?): Please look at the .csproj files

2021-03-30 16:33 UTC, jonashoelzel requested changes
Schau dir die Sachen die ich kommentiert habe nochmal an

2021-03-30 16:33 UTC, jonashoelzel commented on .gitignore
> +*.xlsx
Kannst du hier bitte den genauen Pfad der Datei angeben? Sonst werden alle excel Dateien ignoriert.

2021-03-30 16:33 UTC, jonashoelzel commented on src/BlazorElectron/BlazorElectron.csproj
> +    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
Das ist nicht so cool! Schau mal dass du dein Antivierenporgramm anders einstellst. Zur Not kann man auch contitions machen:

`<PropertyGroup Condition="'$(Configuration)'=='Release'">
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
</PropertyGroup>`

Probier da mal noch bisschen was aus!

2021-03-30 16:33 UTC, jonashoelzel commented on src/ExcelIOComponentTest/DataSetlIOComponentTest.csproj
> +    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
siehe oben!

2021-03-30 16:33 UTC, jonashoelzel commented on src/BlazorElectron/Data/DataLogic/Logic.cs
> +            string fileName = @"\ExcelDataBase.xlsx.xlsx";
Wieso .xlsx.xlsx ??

2021-03-31 10:47 UTC, YeGaSoft commented on src/BlazorElectron/Data/DataLogic/Logic.cs
> +            string fileName = @"\ExcelDataBase.xlsx";
.xlsx.xlsx gefixed.

2021-03-31 11:02 UTC, YeGaSoft commented on .gitignore
> +*.xlsx
Solved.

2021-03-31 11:03 UTC, YeGaSoft commented on src/BlazorElectron/Data/DataLogic/Logic.cs
> +            string fileName = @"\ExcelDataBase.xlsx.xlsx";
Solved.

2021-03-31 11:05 UTC, YeGaSoft commented
Die gitignore wurde angepasst, dass xlsx.xlsx wurde entfernt und die Probleme mit dem RuntimeIdentifier gelöst.

2021-03-31 11:09 UTC, YeGaSoft reviewed
All changes were made and problems resolved.

2021-03-31 21:37 UTC, jonashoelzel commented
Hab die .gitignore noch etwas aufgeräumt

2021-03-31 21:39 UTC, merged